# Generated by Django 5.2.7 on 2025-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_author_alter_book_genre_alter_book_isbn_and_more'),
    ]

    # These fields were already removed from the database, so this migration
    # should not try to drop them again.
    operations = []
