# Generated by Django 5.2.7 on 2025-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_genre_alter_book_isbn'),
    ]

    operations = [
        # category, created_at, description, cover_url are already handled
        # so we only change defaults for stock and available_count.

        migrations.AlterField(
            model_name='book',
            name='available_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
