# Generated by Django 5.2.7 on 2025-11-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_category_remove_book_created_at_and_more'),
    ]

    # category, created_at, description and cover_url are already dealt with
    # so this migration should do nothing.
    operations = []
