# Generated by Django 5.2.7 on 2025-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
